INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRICE, WARRANTY_YEARS, IMAGE, STATUS, CATAGORY_ID) VALUES (50065, 'Nova P32 CURVED MONITOR', 34694.00, 2.54, 'something.jpeg', 'continued', 9);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRICE, WARRANTY_YEARS, IMAGE, STATUS, CATAGORY_ID) VALUES (50066, 'Nova P32 UHD 8K MONITOR', 22117.00, 3.19, 'something.jpeg', 'continued', 9);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRICE, WARRANTY_YEARS, IMAGE, STATUS, CATAGORY_ID) VALUES (50067, 'Nova E27 UHD 8K MONITOR', 35883.00, 2.72, 'something.jpeg', 'continued', 9);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRICE, WARRANTY_YEARS, IMAGE, STATUS, CATAGORY_ID) VALUES (50068, 'Nova P32 UHD 4K MONITOR', 27542.00, 4.62, 'something.jpeg', 'continued', 9);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRICE, WARRANTY_YEARS, IMAGE, STATUS, CATAGORY_ID) VALUES (50069, 'Nova E27 UHD 4K MONITOR', 28070.00, 3.89, 'something.jpeg', 'continued', 9);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRICE, WARRANTY_YEARS, IMAGE, STATUS, CATAGORY_ID) VALUES (50070, 'Nova E27 FHD MONITOR', 24275.00, 2.57, 'something.jpeg', 'continued', 9);
