DECLARE
    v_curr_date DATE;
BEGIN
    v_curr_date := TRUNC(ADD_MONTHS(SYSDATE, -36), 'MONTH') + 2;
    WHILE (v_curr_date < SYSDATE) LOOP
        DBMS_OUTPUT.PUT_LINE(v_curr_date);
        DBMS_OUTPUT.PUT_LINE(v_curr_date+15);
        v_curr_date := ADD_MONTHS(v_curr_date, 1) ;
        
        INSERT INTO SHIPMENT_REQUEST
        SELECT SHIPMENT_REQUEST_ID_SEQ.NEXTVAL, v_curr_date, 'PROCESSED', S.SHOP_ID
        FROM SHOPS S;

        INSERT INTO SHIPMENT_REQUEST
        SELECT SHIPMENT_REQUEST_ID_SEQ.NEXTVAL, v_curr_date+15, 'PROCESSED', S.SHOP_ID
        FROM SHOPS S;
        
        
        DBMS_OUTPUT.PUT_LINE('Here I am');
        
        INSERT INTO SHIPMENT_REQUEST_PRODUCT(PRODUCT_ID, REQUEST_ID, QUANTITY, SUPPLIABLE_AMOUNT)
        SELECT P.PRODUCT_ID, SR.REQUEST_ID, FLOOR(DBMS_RANDOM.VALUE(10, 21)), FLOOR(DBMS_RANDOM.VALUE(10, 15))
        FROM PRODUCTS P, SHIPMENT_REQUEST SR
        WHERE SR.STATUS='PROCESSED';
        
        UPDATE SHIPMENT_REQUEST SET STATUS='CLOSED';

    END LOOP;
END;
/
