
DECLARE
    v_curr_date DATE;
BEGIN
    insert INTO INVENTORY_PRODUCTS (INVENTORY_ID, PRODUCT_ID, QUANTITY)
    SELECT INV.INVENTORY_ID, P.PRODUCT_ID, 0
    FROM INVENTORY INV, PRODUCTS P;
    v_curr_date := TRUNC(ADD_MONTHS(SYSDATE, -36), 'MONTH') + 1;
    WHILE (v_curr_date < SYSDATE) LOOP
        DBMS_OUTPUT.PUT_LINE(v_curr_date);
        DBMS_OUTPUT.PUT_LINE(v_curr_date+15);
        v_curr_date := ADD_MONTHS(v_curr_date, 1) ;
        INSERT INTO INVENTORY_LOT 
        SELECT INVENTORY_LOT_ID_SEQ.NEXTVAL, v_curr_date, F.FACTORY_ID, INV.INVENTORY_ID
        FROM FACTORY F, INVENTORY INV;
        
        INSERT INTO INVENTORY_LOT_PRODUCTS
        SELECT IL.LOT_ID, PD.PRODUCT_ID, FLOOR(DBMS_RANDOM.VALUE(100, 250)), 
            ROUND(DBMS_RANDOM.VALUE(0.6, 1.4), 2) * PD.PRICE, v_curr_date-1
        FROM INVENTORY_LOT IL, PRODUCTS PD
        WHERE IL.SUPPLY_DATE=v_curr_date;
        
        v_curr_date := v_curr_date+15;

        INSERT INTO INVENTORY_LOT 
        SELECT INVENTORY_LOT_ID_SEQ.NEXTVAL, v_curr_date, F.FACTORY_ID, INV.INVENTORY_ID
        FROM FACTORY F, INVENTORY INV;

        INSERT INTO INVENTORY_LOT_PRODUCTS
        SELECT IL.LOT_ID, PD.PRODUCT_ID, FLOOR(DBMS_RANDOM.VALUE(250, 250)), 
            ROUND(DBMS_RANDOM.VALUE(0.6, 1.4), 2) * (SELECT PRICE FROM PRODUCTS P WHERE P.PRODUCT_ID=PD.PRODUCT_ID),
            v_curr_date-1
        FROM INVENTORY_LOT IL, PRODUCTS PD
        WHERE IL.SUPPLY_DATE=v_curr_date;
        v_curr_date := v_curr_date+15;
    END LOOP;
    FOR INF IN (SELECT IL.INVENTORY_ID, ILP.PRODUCT_ID, ILP.QUANTITY FROM INVENTORY_LOT_PRODUCTS ILP JOIN INVENTORY_LOT IL ON(ILP.LOT_ID=IL.LOT_ID)) LOOP
        UPDATE INVENTORY_PRODUCTS SET QUANTITY = QUANTITY+INF.QUANTITY
        WHERE PRODUCT_ID=INF.PRODUCT_ID AND INVENTORY_ID=INF.INVENTORY_ID;
    END LOOP;
END;
/


DECLARE
BEGIN
    insert INTO INVENTORY_PRODUCTS (INVENTORY_ID, PRODUCT_ID, QUANTITY)
    SELECT INV.INVENTORY_ID, P.PRODUCT_ID, 0
    FROM INVENTORY INV, PRODUCTS P;
    FOR INF IN (SELECT IL.INVENTORY_ID, ILP.PRODUCT_ID, ILP.QUANTITY FROM INVENTORY_LOT_PRODUCTS ILP JOIN INVENTORY_LOT IL ON(ILP.LOT_ID=IL.LOT_ID)) LOOP
        UPDATE INVENTORY_PRODUCTS SET QUANTITY = QUANTITY+INF.QUANTITY
        WHERE PRODUCT_ID=INF.PRODUCT_ID AND INVENTORY_ID=INF.INVENTORY_ID;
    END LOOP;
END;