SELECT * FROM AREAS;
SELECT * FROM REGION;
SELECT * FROM JOBS;
SELECT * FROM EMPLOYEES;
SELECT * FROM SHOP_MANAGER;
SELECT * FROM SUPPLY_MANAGER;
SELECT * FROM PRODUCTION_MANAGER;
SELECT * FROM CASHIER;
SELECT * FROM SHOPS;
SELECT * FROM INVENTORY;
SELECT * FROM FACTORY;
SELECT * FROM INVENTORY_LOT;
SELECT * FROM INVENTORY_LOT_PRODUCTS;
SELECT * FROM INVENTORY_PRODUCTS;
SELECT SUM(SUPPLIABLE_AMOUNT) FROM SHIPMENT_REQUEST_PRODUCT
GROUP BY PRODUCT_ID;
SELECT * FROM SHIPMENT_REQUEST;

SELECT * FROM SHIPMENT ORDER BY SHIPMENT_ID;
-- test
SELECT * FROM INVENTORY_PRODUCTS
ORDER BY INVENTORY_ID;

SELECT * FROM SHIPMENT_REQUEST_PRODUCT WHERE REQUEST_ID = 1012;
SELECT * FROM SHIPMENT WHERE SHIPMENT_ID = 1012;

SELECT * FROM SHOP_PRODUCTS;
SELECT * FROM SHOP_PRODUCTS WHERE SHOP_ID = 30004;

SELECT * FROM CUSTOMERS;


SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;
SELECT * FROM SHOP_MANAGER;
SELECT * FROM PRODUCTION_MANAGER;
SELECT * FROM SUPPLY_MANAGER;
SELECT * FROM CASHIER;
SELECT * FROM CUSTOMERS;
SELECT * FROM CATAGORY;
SELECT * FROM PRODUCTS;
SELECT * FROM FACTORY;
SELECT * FROM INVENTORY;
SELECT * FROM INVENTORY_LOT;
SELECT * FROM INVENTORY_LOT_PRODUCTS;
SELECT * FROM INVENTORY_PRODUCTS;
SELECT * FROM SHIPMENT;
SELECT * FROM SHIPMENT_REQUEST;
SELECT * FROM SHIPMENT_REQUEST_PRODUCT;
SELECT * FROM SHIPMENT_PRODUCT;
SELECT * FROM AREAS;
SELECT * FROM REGION;
SELECT * FROM PRODUCT_ALLOTEMENT;
SELECT * FROM SHOPS;
SELECT * FROM SHOP_PRODUCTS;
SELECT * FROM PURCHASE ORDER BY PURCHASE_ID ASC;
SELECT * FROM PURCHASED_PRODUCT;

SELECT FLOOR(DBMS_RANDOM.VALUE(0, 2)) FROM SHIPMENT_REQUEST_PRODUCT;

SELECT * FROM SHOP_PRODUCTS WHERE SHOP_ID=30001 ORDER BY PRODUCT_ID ASC;

SELECT PRICE FROM PRODUCTS WHERE PRODUCT_ID=50001;


